- name: EPEL enabled
  yum:
    name: epel-release
    state: present
  when: ansible_pkg_mgr == 'yum'
  become: root
  tags: root

- name: yum packages installed
  yum:
    name:
      - python34-pip
      - git
      - python34-setuptools     # For uwsgi pip install
      - uwsgi-plugin-python3    # For using flask modules
      - uwsgi-logger-systemd    # For logging uwsgi
      - python34-devel  # For uwsgi pip install
      - gcc     # For uwsgi pip install
      - net-tools       # for netstat (debugging)
      - python-virtualenv
      - sudo
      - libxml2-devel   # For lxml pip install
      - libxml2-python  # For lxml pip install
      - libxslt-devel   # For lxml pip install
  when: ansible_pkg_mgr == 'yum'
  become: root
  tags: root

- name: server pip packages
  pip:
    executable: pip3
    name:
      - setuptools      # For uwsgi pip install
      - uwsgi   # HTTP-compatible server for running as service
      - uwsgiconf
  become: root

- name: get uwsgi path
  shell: "command -v uwsgi"
  register: uwsgi_path
  changed_when: false

- name: app pip packages for virtualenv
  pip:
    name:
      - flask
      - markovify       # App dependency
      - bs4     # App dependency
      - nltk    # App dependency
      - lyricwikia
      - spotipy
      - textstat
      - lxml
    virtualenv: "{{ app_virtualenv }}"
    virtualenv_command: virtualenv
    virtualenv_python: python3
    virtualenv_site_packages: yes
  become: yes
  become_user: "{{ app_user }}"

- name: punkt installed by nltk downloader
  changed_when: false
  command: "{{ app_virtualenv }}/bin/python3 -m nltk.downloader punkt"
  become: yes
  become_user: "{{ app_user }}"
