- name: EPEL enabled
  yum:
    name: epel-release
    state: present

- name: packages installed
  yum:
    name:
      - python34-pip
      - git
      - python34-setuptools     # For uwsgi pip install
      - uwsgi-plugin-python3    # For using flask modules
      - python34-devel  # For uwsgi pip install
      - gcc     # For uwsgi pip install
      - net-tools       # for netstat (debugging)

- name: pip packages
  pip:
    executable: pip3
    name:
      - setuptools      # For uwsgi pip install
      - flask
      - markovify       # App dependency
      - bs4     # App dependency
      - nltk    # App dependency
      - uwsgi   # HTTP-compatible server
      - uwsgiconf
