- name: EPEL enabled
  yum:
    name: epel-release
    state: present
  when: ansible_pkg_mgr == 'yum'
  become: root

- name: yum packages installed
  yum:
    name:
      - python34-pip
      - git
      - python34-setuptools     # For uwsgi pip install
      - uwsgi-plugin-python3    # For using flask modules
      - python34-devel  # For uwsgi pip install
      - gcc     # For uwsgi pip install
      - net-tools       # for netstat (debugging)
      - python-virtualenv
  when: ansible_pkg_mgr == 'yum'
  become: root

- name: apt packages installed
  apt:
    name:
      - python3-pip
      - git
      - python3-setuptools     # For uwsgi pip install
      - uwsgi-plugin-python3    # For using flask modules
      - python3-dev  # For uwsgi pip install
      - gcc     # For uwsgi pip install
      - net-tools       # for netstat (debugging)
      - python-virtualenv
  when: ansible_pkg_mgr == 'apt'
  become: root

- name: server pip packages
  pip:
    executable: pip3
    name:
      - setuptools      # For uwsgi pip install
      - uwsgi   # HTTP-compatible server for running as service
      - uwsgiconf
  become: root

- name: get uwsgi path
  shell: "command -v uwsgi"
  register: uwsgi_path
  changed_when: false

- name: app pip packages for virtualenv
  pip:
    name:
      - flask
      - markovify       # App dependency
      - bs4     # App dependency
      - nltk    # App dependency
    virtualenv: "{{ app_virtualenv }}"
    virtualenv_command: virtualenv
    virtualenv_python: python3
    virtualenv_site_packages: yes
