- name: EPEL enabled
  yum:
    name: epel-release
    state: present

- name: packages installed
  yum:
    name:
      - python34-pip
      - git
      - python34-setuptools     # For uwsgi pip install
      - uwsgi-plugin-python3    # For using flask modules
      - python34-devel  # For uwsgi pip install
      - gcc     # For uwsgi pip install
      - net-tools       # for netstat (debugging)
      - python-virtualenv

- name: server pip packages
  pip:
    executable: pip3
    name:
      - setuptools      # For uwsgi pip install
      - uwsgi   # HTTP-compatible server for running as service
      - uwsgiconf

- name: app pip packages for virtualenv
  pip:
    name:
      - flask
      - markovify       # App dependency
      - bs4     # App dependency
      - nltk    # App dependency
    virtualenv: "{{ app_virtualenv }}"
    virtualenv_command: virtualenv
    virtualenv_python: python3
    virtualenv_site_packages: yes
