- name: template uwsgi systemd service file
  template:
    src: systemd.j2
    dest: "{{ service_file_dest }}"
  # Notify in case of, e.g. port change
  notify: restart uwsgi

- name: uwsgi enabled and started
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: "{{ service_file_name }}"
