galaxy_info:
  author: Jesse Bulson-Lewis
  description: Deploy flowriter_studio
  company: Whitman College

  license: GPLv3

  min_ansible_version: 1.2

  platforms:
  - name: CentOS
    versions:
      - 7

  galaxy_tags: []

dependencies: []
